---
title: "Competitive analysis E-commerce"
---

In this case study, you will step into the shoes of a market researcher for an e-commerce company. Your task is to conduct a comprehensive competitive analysis. 

You'll analyze key competitors and examine customer reviews and social media mentions to gauge public sentiment and identify any areas where your company could potentially gain a competitive advantage. 

Through this process, you'll gain practical experience in data collection, quantitative analysis, and critical evaluation skills, which are crucial in strategic decision-making.

For this case study, we will create a fictional scenario where we have three major e-commerce competitors: E-ShopA, E-ShopB, and E-ShopC. We'll use SQL and Python for data analysis and visualization.

## First analysis

Use SQL queries to analyze your data:

1. Calculate the average annual revenue for each e-shop.

<!--

```sql
SELECT eshop_name, AVG(annual_revenue) as average_revenue
FROM ecommerce_data
GROUP BY eshop_name;
E-Shop with the Highest Average Rating
```
-->

2. Find the e-shop with the highest average rating


<!-- 
```sql
SELECT eshop_name, AVG(average_rating) as average_rating
FROM ecommerce_data
GROUP BY eshop_name
ORDER BY average_rating DESC
LIMIT 1;
E-Shop Performance Over Time
```
 -->

3. Calculate the total annual revenue for each e-shop, for each year.

<!-- 
```sql
SELECT eshop_name, YEAR(date) as year, SUM(annual_revenue) as total_revenue
FROM ecommerce_data
GROUP BY eshop_name, year;
``` 
-->


4. What is the E-Shop with the most Social Media Followers?

<!-- 
```sql
SELECT eshop_name, MAX(social_media_followers) as max_followers
FROM ecommerce_data
GROUP BY eshop_name
ORDER BY max_followers DESC
LIMIT 1;
``` 
-->


5. Show the growth of the active user base each month for each e-shop:

<!-- 
```sql
SELECT eshop_name, DATE_FORMAT(date, '%Y-%m') as month, AVG(active_user_base) as average_active_users
FROM ecommerce_data
GROUP BY eshop_name, month;
``` 
-->

